### ISSUE TITLE
The final performance?

### ISSUE THREAD

**Issue by ZeratuuLL** [JoshVarty/Crawler#1]
Hello! I am also trying to work this environment out! I only see the codes here but there is no result showed. What's the final performance you got? Thank you!

**Comment by JoshVarty** [comment]
I kept running into issues with `NaNs` (the environment seems to return `nan` when your agent walks too far off to the sides or something) so I didn't pursue this very long. Unfortunately I don't remember the final score :(

I do remember that although it could walk, it was not near the ideal walking/running behavior and would often end upside down.

**Comment by ZeratuuLL** [comment]
Oh thank you for replying! Yeah I ran into ```nan``` a lot as well. Now I see why lol. But later I constrained the actions to be within (-1,1) and that is solved at least.

**Comment by JoshVarty** [comment]
Interesting maybe I should give that a shot as well. Out of curiosity were you able to solve this task?

**Comment by ZeratuuLL** [comment]
I can get some reward around 400. Far from the 2000 benchmark.... Still tuning hyperparameters...
